### PR TITLE
Added in the tutorial and use case files for the first time

### PR DESCRIPTION
**Pull request by gsekhon1**
Pls confirm changes to quotes, date format

### CODE REVIEW

**Comment by andymouk** [comment]
Looking good to me - some notes below on `LUSID Excel - Setting up your market data.xlsx`:

Only issue I see with the calcs is in _Add property definition_ (step-2) for _WorldDate_ which is giving me: `#ERROR: lusidInstrumentId is a required property for UpsertInstrumentPropertyRequest and cannot be null` even though this seems to calc correctly on the previous sheet.
- *NOTE: I think this is due to a mismatch between the Web API and SDK API*

Suggest we remove the box-out containing _Figi_ from the _List identifiers_ sheet as it's not an input to the functions used there.

Suggest we call out the input columns and output columns with different shades of header (e.g muted orange for inputs). If we stick to a convention it should become obvious to the user.

Just a note to check the _DateTime format_ sheet which looked possibly out of date.

**Comment by andymouk** [comment]
A couple of additional points relating to possible Add-in changes looking at these worked examples (in `LUSID Excel - Setting up your market data.xlsx`):

1. Should we call out the range supporting parameters in the tooltips somehow (e.g. `flInstrumentsLookup` in _Get instument definition_)? 
2. Should we abstract the `DataTypeIds` passed through to Lusid (e.g. `flPropertiesAdd` in _Add property definition_)? `system:date` etc seems like it's exposing the underlying .Net infrastructure too much.

**Comment by andymouk** [comment]
A few extra observations on `LUSID Excel - Setting up your market data.xlsx`:

_Get instrument definition_
* Spare column on _K_
* Cells in _J_ formatted as `Number` (should it be general)

_Add property definition_
* Spare column on _M_

**Comment by andymouk** [comment]
Some general thoughts:

* Maybe call out some of the other templates (as per `flInstrumentsAdd_Template`), e.g. `flInstrumentPropertiesAdd_Template` as this introduces a new pattern with `Properties...`
* Maybe call out the tooltips on the template header cells.
* Casing on the worksheet names is inconsistent in places. Personal opinion would be to stick with capitalizing the first letter of the first word only, e.g. _View transactions_
* Help topics, add excel function help (pending url alias?, more work?), Lusid help topics for, e.g. scope

**Comment by andymouk** [comment]
`LUSID Excel - Setting up your IBOR template Global Equity Fund.xlsx`

* _Run Valuation_ is there any way to call out how the contents of _inline recipe_ are determined?
* _Perform a reconciliation_ tried this with the instructions but only got a _Right Units_ value back - rest of row blank - is this expected?
* _Set Holdings_ - may be worth deleting row 39 as it shows the tooltips for a previously used template (cell contents since deleted).

**Comment by andymouk** [comment]
> * Help topics, add excel function help (pending url alias?, more work?), Lusid help topics for, e.g. scope

- I See _LUSID Excel - Business Agility - Making Simple Changes Quickly & Easily.xlsx_ calls some of these out - nice

**Comment by andymouk** [comment]
_LUSID Excel - Business Agility - Making Simple Changes Quickly & Easily.xlsx_

* Mixture of Arial and Calibri - would suggest standardise on Calibri
* Header (black) section differs in format from the other sheets
* _Create your instrument universe_ - spare table header at column _M_
* _Create your test environment_ - spare table header at column _N_

**Comment by gsekhon1** [comment]
addressed all of the above!

**Pull request merged**
